/** Semantic palette: screens use meaning, never literal paint values. */
export const colors = {
  background: '#F7F5EF',
  surface: '#FFFFFF',
  surfaceRaised: '#FFFEFA',
  surfaceMuted: '#EEEAE0',
  text: '#1E2A24',
  textMuted: '#687168',
  textSubtle: '#8B928B',
  textInverse: '#FFFFFF',
  border: '#DEDACE',
  borderStrong: '#B9B4A9',
  primary: '#315C42',
  primaryPressed: '#254632',
  primaryForeground: '#FFFFFF',
  primarySoft: '#DDEBDD',
  secondary: '#E7E2D7',
  secondaryForeground: '#1E2A24',
  success: '#2B7047',
  successSoft: '#DDEBDD',
  warning: '#A96118',
  warningSoft: '#F8E8D1',
  danger: '#A64032',
  dangerSoft: '#F5DDD8',
  overlay: 'rgba(24, 31, 27, 0.48)',
  skeleton: '#E5E1D7',
} as const;
