import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useApp } from '@/context/app-context';
import { colors, radius, Screen, ScreenReveal, shadows, spacing, typography, VaataIcon, type VaataIconName } from '@/ui';
import type { UserRole } from '@/types/domain';

const options: { role: UserRole; audience: string; title: string; copy: string; action: string; tone: 'dark' | 'light'; icon: VaataIconName }[] = [
  { role: 'donor', audience: 'For people with food to share', title: 'Start a rescue', copy: 'Pass on good surplus food to a nearby organisation that can use it today.', action: 'Donate food', tone: 'dark', icon: 'share' },
  { role: 'ngo', audience: 'For rescue coordinators', title: 'Keep food moving', copy: 'Find available donations, check the handoff, and coordinate the next stop.', action: 'Open rescue desk', tone: 'light', icon: 'rescue' },
];

/** Role is chosen only at login; cards have one generous and reliable tap target each. */
export default function RoleScreen() {
  const router = useRouter(); const { setRole } = useApp();
  const choose = (role: UserRole) => { setRole(role); router.replace((role === 'donor' ? '/donor/home' : '/ngo/home') as never); };
  return <Screen><ScreenReveal><View style={styles.intro}><View style={styles.brandRow}><View style={styles.brandMark}><VaataIcon name="food" size={21} color={colors.primary} /></View><Text style={styles.brand}>Vaata</Text></View><Text style={styles.title}>What brings you here today?</Text><Text style={styles.subtitle}>Choose the workspace that fits what you need to do right now.</Text></View></ScreenReveal><ScreenReveal delay={70}><View style={styles.options}>{options.map((option) => <Pressable key={option.role} accessibilityRole="button" accessibilityLabel={option.action} onPress={() => choose(option.role)} android_ripple={{ color: option.tone === 'dark' ? colors.rippleInverse : colors.ripple }} pressRetentionOffset={spacing.lg} style={({ pressed }) => [styles.pressable, pressed && styles.pressed]}><View style={[styles.option, option.tone === 'dark' ? styles.darkOption : styles.lightOption]}><View style={styles.topline}><View style={[styles.iconTile, option.tone === 'dark' ? styles.darkIconTile : styles.lightIconTile]}><VaataIcon name={option.icon} size={24} color={option.tone === 'dark' ? colors.frost : colors.primary} /></View><Text style={[styles.audience, option.tone === 'dark' && styles.inverseAudience]}>{option.audience}</Text></View><View style={styles.optionCopy}><Text style={[styles.optionTitle, option.tone === 'dark' && styles.inverseTitle]}>{option.title}</Text><Text style={[styles.optionBody, option.tone === 'dark' && styles.inverseBody]}>{option.copy}</Text></View><View style={[styles.action, option.tone === 'dark' ? styles.darkAction : styles.lightAction]}><Text style={[styles.actionLabel, option.tone === 'dark' && styles.darkActionLabel]}>{option.action}</Text><VaataIcon name="arrow" size={16} color={option.tone === 'dark' ? colors.text : colors.primary} /></View></View></Pressable>)}</View></ScreenReveal><Text style={styles.footer}>You can return to this choice when you sign in again.</Text></Screen>;
}
const styles = StyleSheet.create({ intro: { paddingTop: spacing.xl, gap: spacing.sm }, brandRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, brandMark: { width: 34, height: 34, borderRadius: radius.md, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.primarySoft }, brand: { ...typography.heading3, color: colors.primary, letterSpacing: 0.4 }, title: { ...typography.display, maxWidth: 330 }, subtitle: { ...typography.body, color: colors.textMuted, maxWidth: 330 }, options: { gap: spacing.lg, marginTop: spacing.md }, pressable: { minHeight: 230, overflow: 'hidden', borderRadius: radius.lg }, pressed: { opacity: 0.9 }, option: { minHeight: 230, padding: spacing.xl, justifyContent: 'space-between', borderRadius: radius.lg, borderWidth: 1 }, darkOption: { backgroundColor: colors.text, borderColor: colors.text, ...shadows.md }, lightOption: { backgroundColor: colors.surfaceRaised, borderColor: colors.border }, topline: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' }, iconTile: { width: 44, height: 44, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, darkIconTile: { backgroundColor: colors.surfaceInverse }, lightIconTile: { backgroundColor: colors.primarySoft }, audience: { ...typography.label, color: colors.primary, flex: 1 }, inverseAudience: { color: colors.frost }, optionCopy: { gap: spacing.sm }, optionTitle: typography.heading2, inverseTitle: { color: colors.textInverse }, optionBody: { ...typography.body, color: colors.textMuted, maxWidth: 300 }, inverseBody: { color: colors.textInverseMuted }, action: { alignSelf: 'flex-start', minHeight: 44, flexDirection: 'row', gap: spacing.sm, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.sm }, darkAction: { backgroundColor: colors.frost }, lightAction: { backgroundColor: colors.primarySoft }, actionLabel: { ...typography.label, color: colors.primary }, darkActionLabel: { color: colors.text }, footer: { ...typography.caption, color: colors.textMuted, textAlign: 'center', marginTop: spacing.sm } });
