import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { DetailRow, StatusPill } from '@/components/donations/donation-card';
import { PrimaryButton, SecondaryButton } from '@/components/ui/buttons';
import { Screen } from '@/components/ui/screen';
import { categoryLabels } from '@/data/mock-donations';
import { AppColors, Layout } from '@/constants/theme';
import { useApp } from '@/context/app-context';
export default function ListingDetailsScreen() { const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { donations, updateDonationStatus } = useApp(); const [loading, setLoading] = useState(false); const donation = donations.find((item) => item.id === id); if (!donation) return <Screen title="Loading listing"><Text>Finding donation…</Text></Screen>; const accept = async () => { setLoading(true); await updateDonationStatus(donation.id, 'accepted'); router.replace(`/ngo/assessment/${donation.id}` as never); }; return <Screen eyebrow={donation.donorType || 'Donation'} title={donation.title} subtitle={`From ${donation.donorName} · ${donation.pickupArea}`} action={<StatusPill status={donation.status} />}><View style={{ backgroundColor: AppColors.surface, borderRadius: Layout.cardRadius, borderWidth: 1, borderColor: AppColors.line, paddingHorizontal: 16 }}><DetailRow label="Food and diet" value={`${categoryLabels[donation.category]} · ${donation.diet === 'veg' ? 'Vegetarian' : 'Non-vegetarian'}`} /><DetailRow label="Quantity" value={`${donation.quantity} · serves about ${donation.estimatedServings}`} /><DetailRow label="Prepared / stored" value={`${donation.preparedAt} · ${donation.storageMethod}`} /><DetailRow label="Pickup address" value={donation.pickupAddress} /><DetailRow label="Available until" value={donation.availableUntil} /><DetailRow label="Donor note" value={donation.notes} /></View><View style={{ padding: 14, backgroundColor: AppColors.amberSoft, borderRadius: 14 }}><Text style={{ color: AppColors.ink, lineHeight: 20 }}>Basic food condition is still to be checked in person. This listing is not a safety guarantee.</Text></View><PrimaryButton label="Accept rescue" loading={loading} onPress={accept} /><SecondaryButton label="Back to listings" onPress={() => router.back()} /></Screen>; }
