import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Badge, Card, colors, spacing, typography } from '@/ui';
import type { DonationDestination } from '@/types/domain';

/** A civic recipient card surfaces capacity and time—information that changes a donor's decision. */
export function DestinationCard({ destination, selected, onPress }: { destination: DonationDestination; selected: boolean; onPress: () => void }) {
  return <Pressable accessibilityRole="radio" accessibilityLabel={`Choose ${destination.name}`} accessibilityState={{ checked: selected }} onPress={onPress} style={({ pressed }) => [styles.pressable, pressed && styles.pressed]}><Card variant={selected ? 'raised' : 'outlined'} style={[styles.card, selected && styles.selected]}><View style={styles.header}><View style={styles.titleCopy}><Text style={typography.heading3}>{destination.name}</Text><Text style={styles.type}>{destination.organisationType} · {destination.area}</Text></View><Badge variant={destination.urgency === 'limited' ? 'warning' : 'success'}>{destination.urgency === 'limited' ? 'Limited window' : 'Open now'}</Badge></View><Text style={styles.accepts}>{destination.accepts}</Text><View style={styles.footer}><Text style={styles.capacity}>{destination.capacityLabel}</Text><Text style={styles.distance}>{destination.distanceLabel}</Text></View><Text style={[styles.window, destination.urgency === 'limited' && styles.windowLimited]}>{destination.availableUntil}</Text>{selected && <Text style={styles.chosen}>This recipient is selected for your donation.</Text>}</Card></Pressable>;
}
const styles = StyleSheet.create({ pressable: { minHeight: 180 }, pressed: { opacity: 0.82 }, card: { minHeight: 180, gap: spacing.sm }, selected: { borderWidth: 2, borderColor: colors.primary, padding: spacing.lg - 1 }, header: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, alignItems: 'flex-start' }, titleCopy: { flex: 1, gap: spacing.xs }, type: { ...typography.caption }, accepts: { ...typography.body, color: colors.text }, footer: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, capacity: { ...typography.label, color: colors.primary }, distance: { ...typography.caption }, window: { ...typography.caption, color: colors.success }, windowLimited: { color: colors.warning }, chosen: { ...typography.caption, color: colors.primary, fontWeight: '800' } });
