import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing, typography } from '@/ui';

/** Big, labelled controls avoid making portion selection dependent on a tiny numeric input. */
export function PortionStepper({ value, onChange }: { value: number; onChange: (value: number) => void }) {
  const decrement = () => onChange(Math.max(1, value - 1)); const increment = () => onChange(value + 1);
  return <View style={styles.wrap}><Text style={typography.label}>Estimated portions</Text><View style={styles.control}><Pressable accessibilityRole="button" accessibilityLabel="Remove one portion" disabled={value <= 1} onPress={decrement} style={({ pressed }) => [styles.button, (pressed || value <= 1) && styles.pressed]}><Text style={styles.symbol}>−</Text></Pressable><View accessibilityRole="text" accessibilityLabel={`${value} portions`} style={styles.value}><Text style={styles.amount}>{value}</Text><Text style={styles.unit}>portions</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Add one portion" onPress={increment} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><Text style={styles.symbol}>+</Text></Pressable></View><Text style={styles.helper}>A close estimate helps recipients plan their next meal service.</Text></View>;
}
const styles = StyleSheet.create({ wrap: { gap: spacing.sm }, control: { minHeight: 72, padding: spacing.sm, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: radius.lg, backgroundColor: colors.surfaceMuted }, button: { minHeight: 52, minWidth: 52, borderRadius: radius.sm, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center' }, pressed: { opacity: 0.52 }, symbol: { color: colors.primary, fontSize: 27, lineHeight: 30, fontWeight: '500' }, value: { alignItems: 'center', gap: spacing.xs }, amount: { ...typography.heading1, color: colors.primary }, unit: { ...typography.caption }, helper: { ...typography.caption } });
