import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { PrimaryButton, SecondaryButton } from '@/components/ui/buttons';
import { TextField } from '@/components/ui/fields';
import { Screen } from '@/components/ui/screen';
import { AppColors, Layout } from '@/constants/theme';
import { useApp } from '@/context/app-context';
const labels = ['Food appears edible', 'No obvious visible spoilage', 'Packaging is acceptable', 'Food is within a reasonable time window', 'Quantity roughly matches the listing', 'Pickup conditions are acceptable'];
export default function AssessmentScreen() { const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { saveAssessment, updateDonationStatus } = useApp(); const [checks, setChecks] = useState(labels.map(() => true)); const [notes, setNotes] = useState(''); const complete = async () => { const result = checks.every(Boolean) ? 'passed' : 'review'; saveAssessment({ donationId: id, appearsEdible: checks[0], noVisibleSpoilage: checks[1], properlyPacked: checks[2], safeTimeWindow: checks[3], quantityVerified: checks[4], pickupConditionsAcceptable: checks[5], result, notes }); await updateDonationStatus(id, 'under_review'); router.replace(`/ngo/pickup/${id}` as never); }; return <Screen eyebrow="Basic condition check" title="Check before collecting" subtitle="Use your judgement. This checklist documents a practical observation, not a safety certification."><View style={styles.list}>{labels.map((label, index) => <Pressable key={label} onPress={() => setChecks((current) => current.map((checked, i) => i === index ? !checked : checked))} accessibilityRole="checkbox" accessibilityState={{ checked: checks[index] }} style={styles.row}><View style={[styles.box, checks[index] && styles.checked]}><Text style={styles.tick}>{checks[index] ? '✓' : ''}</Text></View><Text style={styles.label}>{label}</Text></Pressable>)}</View><TextField label="Notes (optional)" value={notes} onChangeText={setNotes} multiline placeholder="Record anything worth noting" /><PrimaryButton label="Complete check" onPress={complete} /><SecondaryButton label="Back to listing" onPress={() => router.back()} /></Screen>; }
const styles = StyleSheet.create({ list: { backgroundColor: AppColors.surface, borderRadius: Layout.cardRadius, borderWidth: 1, borderColor: AppColors.line, padding: 14, gap: 14 }, row: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 11 }, box: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, borderColor: AppColors.line, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: AppColors.primary, borderColor: AppColors.primary }, tick: { color: '#fff', fontWeight: '900' }, label: { flex: 1, color: AppColors.ink, fontSize: 15, lineHeight: 21, fontWeight: '600' }, });
