import { useLocalSearchParams, useRouter } from 'expo-router';
import { Text, View } from 'react-native';
import { DetailRow, StatusPill } from '@/components/donations/donation-card';
import { ProgressSteps } from '@/components/delivery/progress-steps';
import { PrimaryButton, Screen, SecondaryButton } from '@/ui';
import { AppColors, Layout } from '@/constants/theme';
import { useApp } from '@/context/app-context';
import type { DonationStatus } from '@/types/domain';

const next: Partial<Record<DonationStatus, { status: DonationStatus; label: string }>> = { pickup_started: { status: 'picked_up', label: 'Mark food collected' }, picked_up: { status: 'en_route', label: 'Start delivery' }, en_route: { status: 'delivered', label: 'Mark delivered' } };
/** Delivery state is intentionally manual and local until real dispatch/GPS is in scope. */
export default function DeliveryScreen() { const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { donations, updateDonationStatus } = useApp(); const donation = donations.find((item) => item.id === id); if (!donation) return <Screen title="Loading delivery"><Text>Finding rescue…</Text></Screen>; const action = next[donation.status]; const advance = async () => { if (!action) return; await updateDonationStatus(id, action.status); if (action.status === 'delivered') router.replace(`/ngo/delivery/${id}` as never); }; const isDone = donation.status === 'delivered'; return <Screen eyebrow="Mock delivery tracking" title={isDone ? 'Food rescued successfully.' : 'Guide the rescue forward'} subtitle={isDone ? `${donation.estimatedServings} meals are recorded as redirected.` : 'Status changes are local-only in this mock; no live location is being tracked.'} action={<StatusPill status={donation.status} />}><View style={{ padding: 18, borderRadius: Layout.cardRadius, backgroundColor: AppColors.surface, borderWidth: 1, borderColor: AppColors.line, gap: 22 }}><ProgressSteps status={donation.status} /><DetailRow label="Pickup" value={donation.pickupArea} /><DetailRow label="Destination" value="Saksham Community Kitchen, Koregaon Park" /><DetailRow label="Assigned to" value="You · mock volunteer account" /></View><View style={{ minHeight: 150, borderRadius: Layout.cardRadius, justifyContent: 'center', alignItems: 'center', backgroundColor: AppColors.surfaceMuted, gap: 7 }}><Text style={{ color: AppColors.primary, fontWeight: '900', fontSize: 18 }}>Map placeholder</Text><Text style={{ color: AppColors.muted, textAlign: 'center', paddingHorizontal: 30 }}>Live routes and ETA will connect here later.</Text></View>{action ? <PrimaryButton label={action.label} onPress={advance} /> : <PrimaryButton label="Return to rescue desk" onPress={() => router.replace('/ngo/home' as never)} />}{!isDone && <SecondaryButton label="Back to rescue desk" onPress={() => router.replace('/ngo/home' as never)} />}</Screen>; }
