import { useLocalSearchParams, useRouter } from 'expo-router';
import { Text, View } from 'react-native';
import { DetailRow } from '@/components/donations/donation-card';
import { PrimaryButton, SecondaryButton } from '@/components/ui/buttons';
import { Screen } from '@/components/ui/screen';
import { AppColors, Layout } from '@/constants/theme';
import { useApp } from '@/context/app-context';
/** The pickup plan is a mock handoff; it carries no actual contact, maps, or dispatch integration. */
export default function PickupScreen() { const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { donations, updateDonationStatus } = useApp(); const donation = donations.find((item) => item.id === id); if (!donation) return <Screen title="Loading pickup"><Text>Finding pickup plan…</Text></Screen>; const confirm = async () => { await updateDonationStatus(id, 'pickup_started'); router.replace(`/ngo/delivery/${id}` as never); }; return <Screen eyebrow="Pickup plan" title="Make the handoff clear" subtitle="Confirm the plan before travelling to collect the food."><View style={{ backgroundColor: AppColors.surface, borderRadius: Layout.cardRadius, borderColor: AppColors.line, borderWidth: 1, paddingHorizontal: 16 }}><DetailRow label="Donor" value={donation.donorName} /><DetailRow label="Pickup address" value={donation.pickupAddress} /><DetailRow label="Available until" value={donation.availableUntil} /><DetailRow label="Instructions" value={donation.notes} /><DetailRow label="Mock destination" value="Saksham Community Kitchen, Koregaon Park" /></View><View style={{ padding: 14, borderRadius: 14, backgroundColor: AppColors.primarySoft }}><Text style={{ color: AppColors.ink, lineHeight: 20 }}>Contact, navigation and destination matching are placeholders for this working prototype.</Text></View><PrimaryButton label="Confirm pickup plan" onPress={confirm} /><SecondaryButton label="Back to assessment" onPress={() => router.back()} /></Screen>; }
